-- Private, durable purchase-invoice assessments generated by the API service.
create table if not exists public.purchase_assessments (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  business_date date not null,
  cod_clase text not null,
  num_documento text not null,
  nit_proveedor text,
  nombre_proveedor text,
  content_fingerprint text not null check (content_fingerprint ~ '^[0-9a-f]{64}$'),
  assessment_fingerprint text not null check (assessment_fingerprint ~ '^[0-9a-f]{64}$'),
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'completed', 'fallback', 'failed')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_error_code text,
  next_retry_at timestamptz,
  claim_token uuid,
  claimed_at timestamptz,
  deterministic_metrics jsonb not null default '{}'::jsonb,
  markdown text,
  source_cutoffs jsonb not null default '{}'::jsonb,
  generation_mode text check (generation_mode in ('llm', 'deterministic_fallback')),
  provider text,
  model text,
  analyzer_revision text not null,
  prompt_revision text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint purchase_assessments_invoice_revision_key
    unique (tenant_id, business_date, cod_clase, num_documento, assessment_fingerprint)
);

create index if not exists purchase_assessments_tenant_invoice_idx
  on public.purchase_assessments
    (tenant_id, business_date desc, cod_clase, num_documento, created_at desc);
create index if not exists purchase_assessments_tenant_provider_idx
  on public.purchase_assessments (tenant_id, nit_proveedor, business_date desc);
create index if not exists purchase_assessments_pending_idx
  on public.purchase_assessments (tenant_id, business_date, created_at)
  where status = 'pending';
create index if not exists purchase_assessments_retry_idx
  on public.purchase_assessments (tenant_id, next_retry_at, business_date, created_at)
  where status = 'failed';
create index if not exists purchase_assessments_stale_claim_idx
  on public.purchase_assessments (tenant_id, claimed_at)
  where status = 'processing';

create table if not exists public.purchase_assessment_scan_cursors (
  tenant_id text primary key,
  cursor_business_date date,
  cursor_cod_clase text,
  cursor_num_documento text,
  updated_at timestamptz not null default now(),
  check (
    (cursor_business_date is null and cursor_cod_clase is null and cursor_num_documento is null)
    or
    (cursor_business_date is not null and cursor_cod_clase is not null and cursor_num_documento is not null)
  )
);
create index if not exists purchase_assessment_scan_cursors_updated_idx
  on public.purchase_assessment_scan_cursors (updated_at);

alter table public.purchase_assessments enable row level security;
revoke all on table public.purchase_assessments from public, anon, authenticated;
grant select, insert, update, delete on table public.purchase_assessments to service_role;
alter table public.purchase_assessment_scan_cursors enable row level security;
revoke all on table public.purchase_assessment_scan_cursors from public, anon, authenticated;
grant select, insert, update, delete on table public.purchase_assessment_scan_cursors to service_role;

comment on table public.purchase_assessments is
  'Server-only, tenant-scoped invoice assessments; browser roles have no table privileges.';
comment on table public.purchase_assessment_scan_cursors is
  'Server-only keyset scan cursors for bounded periodic purchase-assessment discovery.';
